backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: content/assets
public_folder: /public

collections:
  - name: "blogs"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{title}}-{{date}}" # this will be filename
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      - {label: "Description", name: "description", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}